In [1]:
import pandas as pd

df_final = pd.read_csv(r"C:\Users\user\Desktop\Data_Analytics_Project2\Data files(CSVs)\Day 1\cleanest_amazon_products.csv")

In [2]:
df_final.head()
df_final.shape

(224, 12)

In [3]:
df_final.head()

,asin,productDescription,category,price,retailPrice,productRating,countReview,salesVolume_clean,price_tier,has_reviews,review_density,prime
0,B0DYK1ZH2D,"CATAN Board Game (6th Edition) Trade, Build & ...",board game,41.99,43.99,4.8,39443,6000.0,premium,True,8200.207900,False
1,B00D8STBHY,"Hasbro Gaming Connect 4 Classic Grid, 4 in a R...",board game,8.89,9.99,4.8,81275,10000.0,budget,True,16897.089397,False
2,B076HK9H7Z,Sorry! Board Game for Kids Ages 6 and Up; Clas...,board game,8.98,9.99,4.8,33742,10000.0,budget,True,7014.968815,False
3,B084D2XQ9F,HUES and CUES - Vibrant Color Guessing Board G...,board game,24.95,0.00,4.7,9848,8000.0,mid,True,2090.870488,False
4,B00000DMF5,Hasbro Gaming Candy Land Kingdom of Sweet Adve...,board game,12.99,0.00,4.8,37195,10000.0,budget,True,7732.848233,False

In [4]:
df_final["has_reviews"] = (df_final["countReview"] > 0).astype(int)

In [5]:
df_final["is_discounted"] = (df_final["price"] < df_final["retailPrice"]).astype(int)

In [6]:
df_final[["countReview", "has_reviews"]].sample(10, random_state=42)

     countReview  has_reviews
9           7624            1
84          9324            1
117         1837            1
144         1838            1
221         5268            1
113         5818            1
68            18            1
104         1863            1
177          148            1
185          478            1

In [7]:
df_final[["countReview", "has_reviews"]].sample(10, random_state=42)

     countReview  has_reviews
9           7624            1
84          9324            1
117         1837            1
144         1838            1
221         5268            1
113         5818            1
68            18            1
104         1863            1
177          148            1
185          478            1

In [8]:
df_final[["price", "retailPrice", "is_discounted"]].sample(10, random_state=42)

      price  retailPrice  is_discounted
9     16.84        19.99              1
84    24.99         0.00              0
117   30.42        32.07              1
144   18.48         0.00              0
221  149.99       159.99              1
113   21.49         0.00              0
68    59.99         0.00              0
104    6.98         0.00              0
177     NaN         0.00              0
185   18.48         0.00              0

In [9]:
import numpy as np

df_final["retailPrice"] = df_final["retailPrice"].replace(0, np.nan)

In [10]:
df_final["is_discounted"] = (
    (df_final["price"] < df_final["retailPrice"])
).astype(float)

In [11]:
df_final[["price", "retailPrice", "is_discounted"]].sample(10, random_state=42)

      price  retailPrice  is_discounted
9     16.84        19.99            1.0
84    24.99          NaN            0.0
117   30.42        32.07            1.0
144   18.48          NaN            0.0
221  149.99       159.99            1.0
113   21.49          NaN            0.0
68    59.99          NaN            0.0
104    6.98          NaN            0.0
177     NaN          NaN            0.0
185   18.48          NaN            0.0

In [12]:
df_final["is_discounted"] = np.where(
    df_final["retailPrice"].notna() & df_final["price"].notna(),
    (df_final["price"] < df_final["retailPrice"]).astype(int),
    np.nan
)

In [13]:
df_final[["price", "retailPrice", "is_discounted"]].sample(10, random_state=42)

      price  retailPrice  is_discounted
9     16.84        19.99            1.0
84    24.99          NaN            NaN
117   30.42        32.07            1.0
144   18.48          NaN            NaN
221  149.99       159.99            1.0
113   21.49          NaN            NaN
68    59.99          NaN            NaN
104    6.98          NaN            NaN
177     NaN          NaN            NaN
185   18.48          NaN            NaN

In [14]:
df_final.to_csv("amazon_products_clean_v3final.csv", index=False)

In [2]:
import pandas as pd

df_final = pd.read_csv(
    r"C:\Users\user\Desktop\Data_Analytics_Project2\Data files(CSVs)\Day 2(And Final)\amazon_products_clean_v3.csv"
)

df_final.head()

,asin,productDescription,category,price,retailPrice,productRating,countReview,salesVolume_clean,price_tier,has_reviews,review_density,prime,is_discounted
0,B0DYK1ZH2D,"CATAN Board Game (6th Edition) Trade, Build & ...",board game,41.99,43.99,4.8,39443,6000.0,premium,1,8200.207900,False,1.0
1,B00D8STBHY,"Hasbro Gaming Connect 4 Classic Grid, 4 in a R...",board game,8.89,9.99,4.8,81275,10000.0,budget,1,16897.089397,False,1.0
2,B076HK9H7Z,Sorry! Board Game for Kids Ages 6 and Up; Clas...,board game,8.98,9.99,4.8,33742,10000.0,budget,1,7014.968815,False,1.0
3,B084D2XQ9F,HUES and CUES - Vibrant Color Guessing Board G...,board game,24.95,NaN,4.7,9848,8000.0,mid,1,2090.870488,False,NaN
4,B00000DMF5,Hasbro Gaming Candy Land Kingdom of Sweet Adve...,board game,12.99,NaN,4.8,37195,10000.0,budget,1,7732.848233,False,NaN

In [3]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   asin                224 non-null    object
 1   productDescription  224 non-null    object
 2   category            224 non-null    object
 3   price               218 non-null    float64
 4   retailPrice         78 non-null     float64
 5   productRating       223 non-null    float64
 6   countReview         224 non-null    int64
 7   salesVolume_clean   218 non-null    float64
 8   price_tier          218 non-null    object
 9   has_reviews         224 non-null    int64
 10  review_density      223 non-null    float64
 11  prime               224 non-null    bool
 12  is_discounted       78 non-null     float64
dtypes: bool(1), float64(6), int64(2), object(4)
memory usage: 21.3+ KB

In [4]:
df_final["has_reviews"] = df_final["has_reviews"].astype("Int64")
df_final["is_discounted"] = df_final["is_discounted"].astype("Int64")

In [5]:
df_final[["has_reviews", "is_discounted"]].dtypes

has_reviews      Int64
is_discounted    Int64
dtype: object

In [6]:
df_final[["has_reviews", "is_discounted"]].sample(10, random_state=42)

     has_reviews  is_discounted
9              1              1
84             1           <NA>
117            1              1
144            1           <NA>
221            1              1
113            1           <NA>
68             1           <NA>
104            1           <NA>
177            1           <NA>
185            1           <NA>

In [7]:
df_final["has_reviews"].value_counts(dropna=False)
df_final["is_discounted"].value_counts(dropna=False)

is_discounted
<NA>    146
1        78
Name: count, dtype: Int64

In [8]:
df_final.to_csv(
    r"C:\Users\user\Desktop\Data_Analytics_Project2\Data files(CSVs)\Day 2(And Final)\amazon_products_clean_v4.csv",
    index=False
)